## Packages

In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
np.random.seed(1)

## Data

In [2]:
# Load CSV files
# Train Data
trainop = pd.read_csv('../data/2024-34-1/data/train_operational_readouts.csv')
trainspec = pd.read_csv('../data/2024-34-1/data/train_specifications.csv')
traintte = pd.read_csv('../data/2024-34-1/data/train_tte.csv')
# Validation Data
vallab = pd.read_csv('../data/2024-34-1/data/validation_labels.csv')
valop = pd.read_csv('../data/2024-34-1/data/validation_operational_readouts.csv')
valspec = pd.read_csv('../data/2024-34-1/data/validation_specifications.csv')
# Test Data
testlab = pd.read_csv('../data/2024-34-1/data/test_labels.csv')
testop = pd.read_csv('../data/2024-34-1/data/test_operational_readouts.csv')
testspec = pd.read_csv('../data/2024-34-1/data/test_specifications.csv')

# Convert to DataFrames
# Train Data
df_trainop = pd.DataFrame(data=trainop)
df_trainspec = pd.DataFrame(data=trainspec)
df_traintte = pd.DataFrame(data=traintte)
# Validation Data
df_vallab = pd.DataFrame(data=vallab)
df_valop = pd.DataFrame(data=valop)
df_valspec = pd.DataFrame(data=valspec)
# Test Data
df_testlab = pd.DataFrame(data=testlab)
df_testop = pd.DataFrame(data=testop)
df_testspec = pd.DataFrame(data=testspec)

# Index
trainop_idx = df_trainop.set_index("vehicle_id").sort_index()
trainop_idx['time_step'] = trainop_idx['time_step'].astype('float32')
testop_idx = df_testop.set_index("vehicle_id").sort_index()
testop_idx['time_step'] = testop_idx['time_step'].astype('float32')
valop_idx = df_valop.set_index("vehicle_id").sort_index()
valop_idx['time_step'] = valop_idx['time_step'].astype('float32')

In [3]:
last_step = df_trainop.groupby("vehicle_id")["time_step"].max()

repaired = df_traintte[df_traintte["in_study_repair"] == 1].copy()
repaired["last_step"] = repaired["vehicle_id"].map(last_step)
repaired["gap"] = repaired["length_of_study_time_step"] - repaired["last_step"]
repaired["gap"].describe()

count    2272.000000
mean        3.873151
std        11.763505
min         0.200000
25%         0.600000
50%         1.800000
75%         4.000000
max       260.000000
Name: gap, dtype: float64

#### Findings:
- All in study time steps are greater than last time given in the train operational readouts data

## Label Generation

![alt text](images/image(5).png)

Equipment health formula: $f(x) = t{\text{failure}_v} - t{\text{step}_v}_i$

where:

$f(x) > 48 =$ class 0

$f(x) <= 48 =$ class 1

$f(x) <= 24 =$ class 2

$f(x) <= 12 =$ class 3

$f(x) <= 6 =$ class 4

In [4]:
def EHI(tfailure, tstepvi):
    """ Computes the time at failue
        at vehicle v minus the time step at vehicle v's ith observation
        and assigns the appropriate class for equipment health.

        Args:
            tfailure (Float): The time the vehicle was last recorded if repaired.
            tsepvi (Float): The current time step of the vehicle.

        Returns:
            ehiclass (Integer): A number spanning 0 to 4 representing a class.
    """

    fx = tfailure - tstepvi

    if fx <= 6:
        ehiclass = 4
    elif fx <= 12:
        ehiclass = 3
    elif fx <= 24:
        ehiclass = 2
    elif fx <= 48:
        ehiclass = 1
    else:
        ehiclass = 0

    return ehiclass

In [5]:
df_labeledtrain = df_trainop.copy()
print("df_trainop shape:", df_trainop.shape)
print("df_labeledtrain shape:", df_labeledtrain.shape)

df_trainop shape: (1122452, 107)
df_labeledtrain shape: (1122452, 107)

In [6]:
failure_time = df_traintte.set_index("vehicle_id")["length_of_study_time_step"]
repair_flag = df_traintte.set_index("vehicle_id")["in_study_repair"]

labels = np.array([
    EHI(failure_time[row.vehicle_id], row.time_step)
    if repair_flag[row.vehicle_id] == 1 else 0
    for row in df_trainop.itertuples()
], dtype=np.int8)

In [7]:
print(labels[:172], '\n')  # This is vehicle 0 and it had no repair performed.
print(labels[546:596])  # This is vehicle 22 and it had a repair performed.

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 1 2 2 2 3 3 3 4]

#### As the time readouts progress the equiment health indicator changes overtime if the vehicle was flagged as repaired.

In [8]:
df_labeledtrain['class_label'] = labels
df_labeledtrain.head()

,vehicle_id,time_step,171_0,666_0,427_0,837_0,167_0,167_1,167_2,167_3,167_4,167_5,167_6,167_7,167_8,167_9,309_0,272_0,272_1,272_2,272_3,272_4,272_5,272_6,272_7,272_8,272_9,835_0,370_0,291_0,291_1,291_2,291_3,291_4,291_5,291_6,291_7,291_8,291_9,291_10,158_0,158_1,158_2,158_3,158_4,158_5,158_6,158_7,158_8,158_9,100_0,459_0,459_1,459_2,459_3,459_4,459_5,459_6,459_7,459_8,459_9,459_10,459_11,459_12,459_13,459_14,459_15,459_16,459_17,459_18,459_19,397_0,397_1,397_2,397_3,397_4,397_5,397_6,397_7,397_8,397_9,397_10,397_11,397_12,397_13,397_14,397_15,397_16,397_17,397_18,397_19,397_20,397_21,397_22,397_23,397_24,397_25,397_26,397_27,397_28,397_29,397_30,397_31,397_32,397_33,397_34,397_35,class_label
0,0,11.2,167985.0,10787.0,7413813.0,2296.0,4110.0,1296420.0,1628265.0,630345.0,1269525.0,4772940.0,2706706.0,222225.0,6240.0,0.0,70.0,1435083.0,857662.0,384579.0,668642.0,7239843.0,398490.0,3887.0,0.0,0.0,0.0,8036751.0,0.0,1227.0,555.0,463.0,925.0,468.0,225.0,535.0,516.0,492.0,729.0,66.0,97056.0,2690052.0,2945268.0,788437.0,687480.0,595164.0,491232.0,532932.0,809628.0,505693.0,858410.0,203.676778,111.911500,147.265389,200.479944,230.306278,277.722417,315.748806,372.164528,864.246250,920.881111,637.901639,744.618944,880.866889,1272.323972,1847.623667,940.785694,2.900083,0.208444,0.056417,0.058444,446956.0,411420.0,203024.0,26636.0,29156.0,7616.0,449537.0,233352.0,139920.0,12648.0,2813.0,224.0,53161.0,178881.0,138250.0,13328.0,3581.0,88.0,16361.0,131601.0,116541.0,13506.0,2856.0,48.0,6337.0,105412.0,95728.0,15609.0,1984.0,8.0,784.0,150228.0,261904.0,93172.0,17874.0,452.0,0
1,0,11.4,167985.0,10787.0,7413813.0,2296.0,4111.0,1302855.0,1628265.0,630345.0,1269526.0,4772940.0,2706706.0,222225.0,6240.0,0.0,70.0,1440661.0,857662.0,384579.0,668642.0,7239843.0,398490.0,3887.0,0.0,0.0,0.0,8040811.0,0.0,1230.0,558.0,463.0,925.0,469.0,226.0,535.0,516.0,493.0,729.0,66.0,97056.0,2693100.0,2947368.0,788437.0,687480.0,595164.0,491232.0,532932.0,809628.0,505693.0,860571.0,204.256750,112.924250,147.265389,201.479944,230.306278,277.722417,315.748806,372.164528,864.246250,920.881111,637.901639,745.618944,880.866889,1272.323972,1847.623667,940.785694,2.900083,0.208444,0.056417,0.058444,446964.0,411420.0,203027.0,26638.0,29157.0,7616.0,451193.0,233354.0,139920.0,12649.0,2813.0,224.0,53210.0,178883.0,138252.0,13328.0,3582.0,88.0,16368.0,131601.0,116542.0,13507.0,2856.0,48.0,6339.0,105413.0,95729.0,15610.0,1984.0,8.0,784.0,150228.0,261905.0,93172.0,17874.0,452.0,0
2,0,19.6,331635.0,14525.0,13683604.0,2600.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,1787736.0,1133132.0,598351.0,1167062.0,12314224.0,460240.0,3887.0,0.0,0.0,0.0,12777022.0,0.0,2136.0,954.0,850.0,1420.0,722.0,412.0,880.0,666.0,586.0,1143.0,162.0,181632.0,4249020.0,4630440.0,1539133.0,1421172.0,1039764.0,749472.0,740724.0,995796.0,574045.0,1379191.0,321.671972,157.312500,193.792833,263.577611,310.711861,366.149250,415.642472,484.391167,1146.111611,1286.536333,900.062917,1123.232556,1449.545611,2140.037472,5046.748278,1151.010139,3.320194,0.218806,0.056778,0.058444,756665.0,647348.0,286811.0,30967.0,31213.0,7745.0,633790.0,423395.0,271940.0,16190.0,3573.0,232.0,75038.0,352791.0,327992.0,17325.0,4451.0,92.0,24028.0,234737.0,216619.0,17000.0,3476.0,48.0,12055.0,167693.0,142900.0,19263.0,2441.0,12.0,1420.0,204832.0,313485.0,106464.0,19306.0,452.0,0
3,0,20.2,354975.0,15015.0,14540449.0,2616.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,1824409.0,1166074.0,634595.0,1233908.0,13275730.0,466753.0,3887.0,0.0,0.0,0.0,13612083.0,0.0,2218.0,1014.0,892.0,1471.0,749.0,425.0,901.0,702.0,589.0,1197.0,174.0,193728.0,4462548.0,4988028.0,1696022.0,1565484.0,1112544.0,789228.0,774588.0,1015104.0,576901.0,1428606.0,331.479028,162.731639,198.104472,269.712889,320.087333,377.478667,425.901361,495.749583,1173.882583,1323.460972,923.099361,1161.893139,1501.973944,2208.782833,5587.856667,1160.593833,3.336417,0.218806,0.056778,0.058444,812577.0,686860.0,302955.0,31927.0,31488.0,7749.0,651902.0,478279.0,292109.0,16755.0,3753.0,232.0,77118.0,394083.0,359060.0,17941.0,4573.0,92.0,25164.0,253706.0,232912.0,17583.0,3573.0,48.0,13199.0,176596.0,150565.0,19832.0,2522.0,12.0,1444.0,211688.0,318901.0,107745.0,19406.0,453.0,0
4,0,21.0,365550.0,15295.0,14966985.0,2720.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70.0,1873614.0,1176071.0,639587.0,1266369.0,13758524.0,474047.0,3887.0,0.0,0.0,0.0,14041353.0,0.0,2272.0,1038.0,910.0,1519.0,773.0,440.0,946.0,727.0,599.0,1233.0,178.0,203568.0,4621885.0,5107368.0,1758350.0,1633717.0,1159656.0,820368.0,792996.0,1030644.0,587234.0,1460547.0,339.563444,166.705583,202.430194,275.669056,327.877944,385.460472,435.321167,506.110639,1201.040833,1351.811444,944.133250,1192.740333,1544.355778,2307.900278,5738.170167,1182.611833,3.367250,0.218806,0.056778,0.058444,843929.0,710424.0,314292.0,32585.0,31896.0,7773.0,665154.0,488271.0,300083.0,17265.0,3998.0,232.0,79222.0,411299.0,371612.0,18614.0,4681.0,92.0,25736.0,268834.0,242477.0,18108.0,3641.0,52.0,13400.0,183724.0,155913.0,20573.0,2562.0,12.0,1445.0,213956.0,323997.0,109514.0,19535.0,454.0,0

In [9]:
df_trainspec.head()

   vehicle_id Spec_0 Spec_1 Spec_2 Spec_3 Spec_4 Spec_5 Spec_6 Spec_7
0           0   Cat0   Cat0   Cat0   Cat0   Cat0   Cat0   Cat0   Cat0
1           2   Cat0   Cat1   Cat1   Cat0   Cat0   Cat0   Cat0   Cat1
2           3   Cat0   Cat1   Cat1   Cat1   Cat0   Cat0   Cat0   Cat1
3           4   Cat0   Cat0   Cat2   Cat1   Cat0   Cat0   Cat0   Cat1
4           5   Cat0   Cat2   Cat2   Cat0   Cat0   Cat0   Cat0   Cat1

In [10]:
df_trainspec = df_trainspec.set_index('vehicle_id')
df_valspec = df_valspec.set_index('vehicle_id')
df_testspec = df_testspec.set_index('vehicle_id')
df_trainspec.head()

           Spec_0 Spec_1 Spec_2 Spec_3 Spec_4 Spec_5 Spec_6 Spec_7
vehicle_id
0            Cat0   Cat0   Cat0   Cat0   Cat0   Cat0   Cat0   Cat0
2            Cat0   Cat1   Cat1   Cat0   Cat0   Cat0   Cat0   Cat1
3            Cat0   Cat1   Cat1   Cat1   Cat0   Cat0   Cat0   Cat1
4            Cat0   Cat0   Cat2   Cat1   Cat0   Cat0   Cat0   Cat1
5            Cat0   Cat2   Cat2   Cat0   Cat0   Cat0   Cat0   Cat1

## Temporal Aggregates
why temporal aggregates:

- Because raw value at one moment doesn't tell the model anything about trajectory and trajectory is what is needed to make predictions in this case.                 
- Sensor read outs trend near linear with degradation = rate of change is the likely one of the most predictive signals.
- XGBoost has no memory across rows so any trajectory information has to be precomputed into the row as an explicit feature.

each sensor gets its own last value, mean, std, slope and delta. class label remains unchanged

In [11]:
def add_temporal_aggregates(df_indexed, sensor_cols):
    """
    Adds expanding-window temporal aggregate features (last, mean, std,
    slope, delta) for every sensor column, computed per vehicle using
    only that vehicle's readings up to and including each row -- never
    future readings, to avoid leakage into earlier-timestep labels.

    All new columns are built in a dict and attached to the dataframe in
    a single concat at the end, rather than assigned one at a time in the
    loop. Assigning columns individually inside a loop over 100+ sensors
    forces pandas to repeatedly reallocate the whole frame's memory
    layout, which is slow and can trigger a "highly fragmented dataframe"
    warning at this dataset's scale -- a single batched concat avoids it.

    Slope is computed via closed-form cumulative sums (a standard
    least-squares trick) rather than .expanding().apply(), since the
    latter calls a Python function once per row per sensor -- far too
    slow at 1.1M+ rows x 105 sensors.

    Args:
        df_indexed (DataFrame): operational readouts, indexed by
            vehicle_id, MUST already be sorted by vehicle_id then
            time_step (expanding logic assumes row order is chronological
            within each vehicle).
        sensor_cols (list of str): sensor column names to aggregate.

    Returns:
        DataFrame: original columns preserved, plus 5 new columns per
            sensor (e.g. "397_0_last", "397_0_mean", "397_0_std",
            "397_0_slope", "397_0_delta").
    """
    df_indexed[sensor_cols] = df_indexed[sensor_cols].astype("float32")

    grouped_by_vehicle = df_indexed.groupby(level=0)
    new_columns = {}  # collect everything here first, attach once at the end

    for sensor in sensor_cols:
        values = df_indexed[sensor]
        valid = values.notna()

        new_columns[f"{sensor}_last"] = values

        new_columns[f"{sensor}_mean"] = grouped_by_vehicle[sensor].expanding().mean().values
        new_columns[f"{sensor}_std"] = grouped_by_vehicle[sensor].expanding().std().values

        first_value = df_indexed.groupby(level=0)[sensor].transform("first")
        new_columns[f"{sensor}_delta"] = values - first_value

        time_step = df_indexed["time_step"]
        x = time_step.where(valid, 0)
        y = values.where(valid, 0)
        xy = (time_step * values).where(valid, 0)
        xx = (time_step ** 2).where(valid, 0)
        n = valid.astype(int)

        tmp = pd.DataFrame({"n": n, "x": x, "y": y, "xy": xy, "xx": xx}, index=df_indexed.index)
        cum = tmp.groupby(level=0).cumsum()

        numerator = cum["n"] * cum["xy"] - cum["x"] * cum["y"]
        denominator = cum["n"] * cum["xx"] - cum["x"] ** 2
        slope = numerator / denominator
        slope[(cum["n"] < 2) | (denominator == 0)] = np.nan

        new_columns[f"{sensor}_slope"] = slope

    # attach all 525 new columns in a single operation, instead of 525
    # separate ones -- this is what actually avoids the fragmentation warning
    aggregates_df = pd.DataFrame(new_columns, index=df_indexed.index)
    df_indexed = pd.concat([df_indexed, aggregates_df], axis=1)

    return df_indexed

In [12]:
# Temporal aggregates and labels for train set
sensorcols = df_trainop.iloc[:, 2:].columns
sensors = [col for col in sensorcols]
df_trainop_temporal = add_temporal_aggregates(trainop_idx, sensors)
df_trainop_temporal = df_trainop_temporal.join(df_trainspec)
df_trainop_temporal['class_label'] = labels

for col in df_trainspec.columns:
    df_trainop_temporal[col] = df_trainop_temporal[col].astype('category')

print(df_trainop_temporal.memory_usage(deep=True).sum() / 1e9, "GB")

df_trainop_temporal.head()

3.795018783 GB

,time_step,171_0,666_0,427_0,837_0,167_0,167_1,167_2,167_3,167_4,167_5,167_6,167_7,167_8,167_9,309_0,272_0,272_1,272_2,272_3,272_4,272_5,272_6,272_7,272_8,272_9,835_0,370_0,291_0,291_1,291_2,291_3,291_4,291_5,291_6,291_7,291_8,291_9,291_10,158_0,158_1,158_2,158_3,158_4,158_5,158_6,158_7,158_8,158_9,100_0,459_0,459_1,459_2,459_3,459_4,459_5,459_6,459_7,459_8,459_9,459_10,459_11,459_12,459_13,459_14,459_15,459_16,459_17,459_18,459_19,397_0,397_1,397_2,397_3,397_4,397_5,397_6,397_7,397_8,397_9,397_10,397_11,397_12,397_13,397_14,397_15,397_16,397_17,397_18,397_19,397_20,397_21,397_22,397_23,397_24,397_25,397_26,397_27,397_28,397_29,397_30,397_31,397_32,397_33,397_34,397_35,171_0_last,171_0_mean,171_0_std,171_0_delta,171_0_slope,666_0_last,666_0_mean,666_0_std,666_0_delta,666_0_slope,427_0_last,427_0_mean,427_0_std,427_0_delta,427_0_slope,837_0_last,837_0_mean,837_0_std,837_0_delta,837_0_slope,167_0_last,167_0_mean,167_0_std,167_0_delta,167_0_slope,167_1_last,167_1_mean,167_1_std,167_1_delta,167_1_slope,167_2_last,167_2_mean,167_2_std,167_2_delta,167_2_slope,167_3_last,167_3_mean,167_3_std,167_3_delta,167_3_slope,167_4_last,167_4_mean,167_4_std,167_4_delta,167_4_slope,167_5_last,167_5_mean,167_5_std,167_5_delta,167_5_slope,167_6_last,167_6_mean,167_6_std,167_6_delta,167_6_slope,167_7_last,167_7_mean,167_7_std,167_7_delta,167_7_slope,167_8_last,167_8_mean,167_8_std,167_8_delta,167_8_slope,167_9_last,167_9_mean,167_9_std,167_9_delta,167_9_slope,309_0_last,309_0_mean,309_0_std,309_0_delta,309_0_slope,272_0_last,272_0_mean,272_0_std,272_0_delta,272_0_slope,272_1_last,272_1_mean,272_1_std,272_1_delta,272_1_slope,272_2_last,272_2_mean,272_2_std,272_2_delta,272_2_slope,272_3_last,272_3_mean,272_3_std,272_3_delta,272_3_slope,272_4_last,272_4_mean,272_4_std,272_4_delta,272_4_slope,272_5_last,272_5_mean,272_5_std,272_5_delta,272_5_slope,272_6_last,272_6_mean,272_6_std,272_6_delta,272_6_slope,272_7_last,272_7_mean,272_7_std,272_7_delta,272_7_slope,272_8_last,272_8_mean,272_8_std,272_8_delta,272_8_slope,272_9_last,272_9_mean,272_9_std,272_9_delta,272_9_slope,835_0_last,835_0_mean,835_0_std,835_0_delta,835_0_slope,370_0_last,370_0_mean,370_0_std,370_0_delta,370_0_slope,291_0_last,291_0_mean,291_0_std,291_0_delta,291_0_slope,291_1_last,291_1_mean,291_1_std,291_1_delta,291_1_slope,291_2_last,291_2_mean,291_2_std,291_2_delta,291_2_slope,291_3_last,291_3_mean,291_3_std,291_3_delta,291_3_slope,291_4_last,291_4_mean,291_4_std,291_4_delta,291_4_slope,291_5_last,291_5_mean,291_5_std,291_5_delta,291_5_slope,291_6_last,291_6_mean,291_6_std,291_6_delta,291_6_slope,291_7_last,291_7_mean,291_7_std,291_7_delta,291_7_slope,291_8_last,291_8_mean,291_8_std,291_8_delta,291_8_slope,291_9_last,291_9_mean,291_9_std,291_9_delta,291_9_slope,291_10_last,291_10_mean,291_10_std,291_10_delta,291_10_slope,158_0_last,158_0_mean,158_0_std,158_0_delta,158_0_slope,158_1_last,158_1_mean,158_1_std,158_1_delta,158_1_slope,158_2_last,158_2_mean,158_2_std,158_2_delta,158_2_slope,158_3_last,158_3_mean,158_3_std,158_3_delta,158_3_slope,158_4_last,158_4_mean,158_4_std,158_4_delta,158_4_slope,158_5_last,158_5_mean,158_5_std,158_5_delta,158_5_slope,158_6_last,158_6_mean,158_6_std,158_6_delta,158_6_slope,158_7_last,158_7_mean,158_7_std,158_7_delta,158_7_slope,158_8_last,158_8_mean,158_8_std,158_8_delta,158_8_slope,158_9_last,158_9_mean,158_9_std,158_9_delta,158_9_slope,100_0_last,100_0_mean,100_0_std,100_0_delta,100_0_slope,459_0_last,459_0_mean,459_0_std,459_0_delta,459_0_slope,459_1_last,459_1_mean,459_1_std,459_1_delta,459_1_slope,459_2_last,459_2_mean,459_2_std,459_2_delta,459_2_slope,459_3_last,459_3_mean,459_3_std,459_3_delta,459_3_slope,459_4_last,459_4_mean,459_4_std,459_4_delta,459_4_slope,459_5_last,459_5_mean,459_5_std,459_5_delta,459_5_slope,459_6_last,459_6_mean,459_6_std,459_6_delta,459_6_slope,459_7_last,459_7_mean,459_7_std,459_7_delta,459_7_slope,459_8_last,459_8_mean,459_8_std,459_8_delta,459_8_slope,459_9_last,459_9_mean,459_9_std,459_9_delta,459_9_slope,459_10_last,459_10_mean,459_10_std,459_10_delta,459_10_slope,459_11_last,459_11_mean,459_11_std,459_11_delta,459_11_slope,459_12_last,459_12_mean,459_12_std,459_12_delta,459_12_slope,459_13_last,459_13_mean,459_13_std,459_13_delta,459_13_slope,459_14_last,459_14_mean,459_14_std,459_14_delta,459_14_slope,459_15_last,459_15_mean,459_15_std,459_15_delta,459_15_slope,459_16_last,459_16_mean,459_16_std,459_16_delta,459_16_slope,459_17_last,459_17_mean,459_17_std,459_17_delta,459_17_slope,459_18_last,459_18_mean,459_18_std,459_18_delta,459_18_slope,459_19_last,459_19_mean,459_19_std,459_19_delta,459_19_slope,397_0_last,397_0_mean,397_0_std,397_0_delta,397_0_slope,397_1_last,397_1_mean,397_1_std,397_1_delta,397_1_slope,397_2_last,397_2_mean,397_2_std,397_2_delta,397_2_slope,397_3_last,397_3_mean,397_3_std,397_3_delta,397_3_slope,397_4_last,397_4_mean,397_4_std,397_4_delta,397_4_slope,397_5_last,397_5_mean,397_5_std,397_5_delta,397_5_slope,397_6_last,397_6_mean,397_6_std,397_6_delta,397_6_slope,397_7_last,397_7_mean,397_7_std,397_7_delta,397_7_slope,397_8_last,397_8_mean,397_8_std,397_8_delta,397_8_slope,397_9_last,397_9_mean,397_9_std,397_9_delta,397_9_slope,397_10_last,397_10_mean,397_10_std,397_10_delta,397_10_slope,397_11_last,397_11_mean,397_11_std,397_11_delta,397_11_slope,397_12_last,397_12_mean,397_12_std,397_12_delta,397_12_slope,397_13_last,397_13_mean,397_13_std,397_13_delta,397_13_slope,397_14_last,397_14_mean,397_14_std,397_14_delta,397_14_slope,397_15_last,397_15_mean,397_15_std,397_15_delta,397_15_slope,397_16_last,397_16_mean,397_16_std,397_16_delta,397_16_slope,397_17_last,397_17_mean,397_17_std,397_17_delta,397_17_slope,397_18_last,397_18_mean,397_18_std,397_18_delta,397_18_slope,397_19_last,397_19_mean,397_19_std,397_19_delta,397_19_slope,397_20_last,397_20_mean,397_20_std,397_20_delta,397_20_slope,397_21_last,397_21_mean,397_21_std,397_21_delta,397_21_slope,397_22_last,397_22_mean,397_22_std,397_22_delta,397_22_slope,397_23_last,397_23_mean,397_23_std,397_23_delta,397_23_slope,397_24_last,397_24_mean,397_24_std,397_24_delta,397_24_slope,397_25_last,397_25_mean,397_25_std,397_25_delta,397_25_slope,397_26_last,397_26_mean,397_26_std,397_26_delta,397_26_slope,397_27_last,397_27_mean,397_27_std,397_27_delta,397_27_slope,397_28_last,397_28_mean,397_28_std,397_28_delta,397_28_slope,397_29_last,397_29_mean,397_29_std,397_29_delta,397_29_slope,397_30_last,397_30_mean,397_30_std,397_30_delta,397_30_slope,397_31_last,397_31_mean,397_31_std,397_31_delta,397_31_slope,397_32_last,397_32_mean,397_32_std,397_32_delta,397_32_slope,397_33_last,397_33_mean,397_33_std,397_33_delta,397_33_slope,397_34_last,397_34_mean,397_34_std,397_34_delta,397_34_slope,397_35_last,397_35_mean,397_35_std,397_35_delta,397_35_slope,Spec_0,Spec_1,Spec_2,Spec_3,Spec_4,Spec_5,Spec_6,Spec_7,class_label
vehicle_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,11.200000,167985.0,10787.0,7413813.0,2296.0,4110.0,1296420.0,1628265.0,630345.0,1269525.0,4772940.0,2706706.0,222225.0,6240.0,0.0,70.0,1435083.0,857662.0,384579.0,668642.0,7239843.0,398490.0,3887.0,0.0,0.0,0.0,8036751.0,0.0,1227.0,555.0,463.0,925.0,468.0,225.0,535.0,516.0,492.0,729.0,66.0,97056.0,2690052.0,2945268.0,788437.0,687480.0,595164.0,491232.0,532932.0,809628.0,505693.0,858410.0,203.676773,111.911499,147.265396,200.479950,230.306274,277.722412,315.748810,372.164520,864.246277,920.881104,637.901611,744.618958,880.866882,1272.323975,1847.623657,940.785706,2.900083,0.208444,0.056417,0.058444,446956.0,411420.0,203024.0,26636.0,29156.0,7616.0,449537.0,233352.0,139920.0,12648.0,2813.0,224.0,53161.0,178881.0,138250.0,13328.0,3581.0,88.0,16361.0,131601.0,116541.0,13506.0,2856.0,48.0,6337.0,105412.0,95728.0,15609.0,1984.0,8.0,784.0,150228.0,261904.0,93172.0,17874.0,452.0,167985.0,167985.0,NaN,0.0,NaN,10787.0,10787.0,NaN,0.0,NaN,7413813.0,7.413813e+06,NaN,0.0,NaN,2296.0,2296.000000,NaN,0.0,NaN,4110.0,4110.0,NaN,0.0,NaN,1296420.0,1296420.0,NaN,0.0,NaN,1628265.0,1628265.0,NaN,0.0,NaN,630345.0,630345.0,NaN,0.0,NaN,1269525.0,1269525.0,NaN,0.0,NaN,4772940.0,4772940.0,NaN,0.0,NaN,2706706.0,2706706.0,NaN,0.0,NaN,222225.0,222225.0,NaN,0.0,NaN,6240.0,6240.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,70.0,70.0,NaN,0.0,NaN,1435083.0,1.435083e+06,NaN,0.0,NaN,857662.0,8.576620e+05,NaN,0.0,NaN,384579.0,384579.000000,NaN,0.0,NaN,668642.0,668642.0,NaN,0.0,NaN,7239843.0,7.239843e+06,NaN,0.0,NaN,398490.0,398490.000000,NaN,0.0,NaN,3887.0,3887.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,8036751.0,8.036751e+06,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,1227.0,1227.00,NaN,0.0,NaN,555.0,555.00,NaN,0.0,NaN,463.0,463.0,NaN,0.0,NaN,925.0,925.00,NaN,0.0,NaN,468.0,468.0,NaN,0.0,NaN,225.0,225.000000,NaN,0.0,NaN,535.0,535.00,NaN,0.0,NaN,516.0,516.0,NaN,0.0,NaN,492.0,492.000000,NaN,0.0,NaN,729.0,729.0,NaN,0.0,NaN,66.0,66.0,NaN,0.0,NaN,97056.0,97056.0,NaN,0.0,NaN,2690052.0,2690052.0,NaN,0.0,NaN,2945268.0,2945268.0,NaN,0.0,NaN,788437.0,788437.00,NaN,0.0,NaN,687480.0,687480.0,NaN,0.0,NaN,595164.0,595164.0,NaN,0.0,NaN,491232.0,491232.0,NaN,0.0,NaN,532932.0,532932.0,NaN,0.0,NaN,809628.0,809628.0,NaN,0.0,NaN,505693.0,505693.0,NaN,0.0,NaN,858410.0,858410.0,NaN,0.0,NaN,203.676773,203.676773,NaN,0.000000,NaN,111.911499,111.911499,NaN,0.000000,NaN,147.265396,147.265396,NaN,0.000000,NaN,200.479950,200.479950,NaN,0.000000,NaN,230.306274,230.306274,NaN,0.000000,NaN,277.722412,277.722412,NaN,0.000000,NaN,315.748810,315.748810,NaN,0.000000,NaN,372.164520,372.164520,NaN,0.000000,NaN,864.246277,864.246277,NaN,0.000000,NaN,920.881104,920.881104,NaN,0.000000,NaN,637.901611,637.901611,NaN,0.000000,NaN,744.618958,744.618958,NaN,0.000000,NaN,880.866882,880.866882,NaN,0.000000,NaN,1272.323975,1272.323975,NaN,0.000000,NaN,1847.623657,1847.623657,NaN,0.000000,NaN,940.785706,940.785706,NaN,0.000000,NaN,2.900083,2.900083,NaN,0.000000,NaN,0.208444,0.208444,NaN,0.000000,NaN,0.056417,0.056417,NaN,0.000000,NaN,0.058444,0.058444,NaN,0.0,NaN,446956.0,446956.0,NaN,0.0,NaN,411420.0,411420.000000,NaN,0.0,NaN,203024.0,203024.00,NaN,0.0,NaN,26636.0,26636.000000,NaN,0.0,NaN,29156.0,29156.0,NaN,0.0,NaN,7616.0,7616.0,NaN,0.0,NaN,449537.0,449537.000000,NaN,0.0,NaN,233352.0,233352.000000,NaN,0.0,NaN,139920.0,139920.000000,NaN,0.0,NaN,12648.0,12648.0,NaN,0.0,NaN,2813.0,2813.000000,NaN,0.0,NaN,224.0,224.000000,NaN,0.0,NaN,53161.0,53161.000000,NaN,0.0,NaN,178881.0,178881.000000,NaN,0.0,NaN,138250.0,138250.0,NaN,0.0,NaN,13328.0,13328.000000,NaN,0.0,NaN,3581.0,3581.000000,NaN,0.0,NaN,88.0,88.000000,NaN,0.0,NaN,16361.0,16361.00,NaN,0.0,NaN,131601.0,131601.000000,NaN,0.0,NaN,116541.0,116541.000000,NaN,0.0,NaN,13506.0,13506.0,NaN,0.0,NaN,2856.0,2856.000000,NaN,0.0,NaN,48.0,48.0,NaN,0.0,NaN,6337.0,6337.000000,NaN,0.0,NaN,105412.0,105412.000000,NaN,0.0,NaN,95728.0,95728.000000,NaN,0.0,NaN,15609.0,15609.000000,NaN,0.0,NaN,1984.0,1984.000000,NaN,0.0,NaN,8.0,8.000000,NaN,0.0,NaN,784.0,784.0,NaN,0.0,NaN,150228.0,150228.000000,NaN,0.0,NaN,261904.0,261904.00,NaN,0.0,NaN,93172.0,93172.000000,NaN,0.0,NaN,17874.0,17874.000000,NaN,0.0,NaN,452.0,452.00,NaN,0.0,NaN,Cat0,Cat0,Cat0,Cat0,Cat0,Cat0,Cat0,Cat0,0
0,11.400000,167985.0,10787.0,7413813.0,2296.0,4111.0,1302855.0,1628265.0,630345.0,1269526.0,4772940.0,2706706.0,222225.0,6240.0,0.0,70.0,1440661.0,857662.0,384579.0,668642.0,7239843.0,398490.0,3887.0,0.0,0.0,0.0,8040811.0,0.0,1230.0,558.0,463.0,925.0,469.0,226.0,535.0,516.0,493.0,729.0,66.0,97056.0,2693100.0,2947368.0,788437.0,687480.0,595164.0,491232.0,532932.0,809628.0,505693.0,860571.0,204.256744,112.924248,147.265396,201.479950,230.306274,277.722412,315.748810,372.164520,864.246277,920.881104,637.901611,745.618958,880.866882,1272.323975,1847.623657,940.785706,2.900083,0.208444,0.056417,0.058444,446964.0,411420.0,203027.0,26638.0,29157.0,7616.0,451193.0,233354.0,139920.0,12649.0,2813.0,224.0,53210.0,178883.0,138252.0,13328.0,3582.0,88.0,16368.0,131601.0,116542.0,13507.0,2856.0,48.0,6339.0,105413.0,95729.0,15610.0,1984.0,8.0,784.0,150228.0,261905.0,93172.0,17874.0,452.0,167985.0,167985.0,0.000000,0.0,12.478294,10787.0,10787.0,0.000000,0.0,0.000000,7413813.0,7.413813e+06,0.000000e+00,0.0,0.000,2296.0,2296.000000,0.000000,0.0,0.000000,4111.0,4110.5,0.707107,1.0,5.069307,1302855.0,1299637.5,4550.232137,6435.0,32243.912109,1628265.0,1628265.0,0.0,0.0,0.0,630345.0,630345.0,0.0,0.0,49.913177,1269526.0,1269525.5,0.707107,1.0,99.826355,4772940.0,4772940.0,0.0,0.0,399.30542,2706706.0,2706706.0,0.0,0.0,0.0,222225.0,222225.0,0.0,0.0,24.956589,6240.0,6240.0,0.0,0.0,0.779893,0.0,0.0,0.0,0.0,0.0,70.0,70.0,0.0,0.0,0.006093,1440661.0,1.437872e+06,3944.241625,5578.0,27851.552734,857662.0,8.576620e+05,0.000000,0.0,0.000000,384579.0,384579.000000,0.000000,0.0,0.000000,668642.0,668642.0,0.000000,0.0,49.913177,7239843.0,7.239843e+06,0.000000e+00,0.0,0.0000,398490.0,398490.000000,0.000000,0.0,49.913177,3887.0,3887.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8040811.0,8.038781e+06,2.870854e+03,4060.0,20763.880859,0.0,0.0,0.0,0.0,0.0,1230.0,1228.50,2.121320,3.0,15.012947,558.0,556.50,2.121320,3.0,14.964204,463.0,463.0,0.000000,0.0,0.048743,925.0,925.00,0.000000,0.0,0.097487,469.0,468.5,0.707107,1.0,4.971820,226.0,225.500000,0.707107,1.0,4.996192,535.0,535.00,0.000000,0.0,0.048743,516.0,516.0,0.000000,0.0,0.000000,493.0,492.500000,0.707107,1.0,5.020564,729.0,729.0,0.000000,0.0,0.000000,66.0,66.0,0.000000,0.0,0.006093,97056.0,97056.0,0.000000,0.0,0.000000,2693100.0,2691576.0,2155.261469,3048.0,15373.257812,2947368.0,2946318.0,1.484924e+03,2100.0,10781.246094,788437.0,788437.00,0.00000,0.0,99.826355,687480.0,687480.0,0.000000,0.0,49.913177,595164.0,595164.0,0.000000,0.0,49.913177,491232.0,491232.0,0.000000,0.0,49.913177,532932.0,532932.0,0.000000,0.0,49.913177,809628.0,809628.0,0.000000,0.0,0.000000,505693.0,505693.0,0.000000,0.0,49.913177,860571.0,859490.5,1528.057754,2161.0,10781.246094,204.256744,203.966759,0.410102,0.579971,2.924600,112.924248,112.417873,0.716121,1.012749,5.057121,147.265396,147.265396,0.000000,0.000000,0.000000,201.479950,200.979950,0.707107,1.000000,5.020564,230.306274,230.306274,0.000000,0.000000,0.024372,277.722412,277.722412,0.000000,0.000000,0.024372,315.748810,315.748810,0.000000,0.000000,0.000000,372.164520,372.164520,0.000000,0.000000,0.000000,864.246277,864.246277,0.000000,0.000000,0.000000,920.881104,920.881104,0.000000,0.000000,0.000000,637.901611,637.901611,0.000000,0.000000,0.048743,745.618958,745.118958,0.707107,1.000000,5.069307,880.866882,880.866882,0.000000,0.000000,0.000000,1272.323975,1272.323975,0.000000,0.000000,0.097487,1847.623657,1847.623657,0.000000,0.000000,0.000000,940.785706,940.785706,0.000000,0.000000,0.097487,2.900083,2.900083,0.000000,0.000000,0.000381,0.208444,0.208444,0.000000,0.000000,0.000024,0.056417,0.056417,0.000000,0.000000,0.000000,0.058444,0.058444,0.0,0.0,5.950114e-06,446964.0,446960.0,5.656854,8.0,49.913177,411420.0,411420.000000,0.000000,0.0,49.913177,203027.0,203025.50,2.121320,3.0,24.956589,26638.0,26637.000000,1.414214,2.0,9.358721,29157.0,29156.5,0.707107,1.0,6.239147,7616.0,7616.0,0.000000,0.0,0.000000,451193.0,450365.000000,1170.968830,1656.0,8285.586914,233354.0,233353.000000,1.414214,2.0,24.956589,139920.0,139920.000000,0.000000,0.0,12.478294,12649.0,12648.5,0.707107,1.0,4.679360,2813.0,2813.000000,0.000000,0.0,0.000000,224.0,224.000000,0.000000,0.0,0.024372,53210.0,53185.500000,34.648232,49.0,249.565872,178883.0,178882.000000,1.414214,2.0,12.478294,138252.0,138251.0,1.414214,2.0,12.478294,13328.0,13328.000000,0.000000,0.0,0.000000,3582.0,3581.500000,0.707107,1.0,5.069307,88.0,88.000000,0.000000,0.0,0.006093,16368.0,16364.50,4.949747,7.0,34.315308,131601.0,131601.000000,0.000000,0.0,0.000000,116542.0,116541.500000,0.707107,1.0,12.478294,13507.0,13506.5,0.707107,1.0,6.239147,2856.0,2856.000000,0.000000,0.0,0.194973,48.0,48.0,0.000000,0.0,0.000000,6339.0,6338.000000,1.414214,2.0,10.138614,105413.0,105412.500000,0.707107,1.0,12.478294,95729.0,95728.500000,0.707107,1.0,12.478294,15610.0,15609.500000,0.707107,1.0,6.239147,1984.0,1984.000000,0.000000,0.0,0.000000,8.0,8.000000,0.000000,0.0,0.000000,784.0,784.0,0.000000,0.0,0.000000,150228.0,150228.000000,0.000000,0.0,12.478294,261905.0,261904.50,0.707107,1.0,24.956589,93172.0,93172.000000,0.000000,0.0,0.000000,17874.0,17874.000000,0.000000,0.0,0.000000,452.0,452.00,0.000000,0.0,0.000000,Cat0,Cat0,Cat0,Cat0,Cat0,Cat0,Cat0,Cat0,0

##### Note to self: 
The temporal aggregates in the training set include trend data that the val and test datasets do not, because the Scania Component X challenge excludes it and provides only the equipment health indicator at the time of the final i'th sensor readout. It might be useful to split the temporal training set into an internal validation set to test trend tracking accuracy in the training loop.

In [13]:
# Temporal aggregates and labels for validation set
sensorcols = df_valop.iloc[:, 2:].columns
sensors = [col for col in sensorcols]
df_valop_temporal = add_temporal_aggregates(valop_idx, sensors)
mask = df_valop_temporal.groupby(level=0).cumcount(ascending=False) == 0
df_valop_temporal = df_valop_temporal.join(df_valspec)
df_valop_temporal['class_label'] = np.nan
df_valop_temporal.loc[mask, 'class_label'] = np.asarray(df_vallab['class_label'])

for col in df_valspec.columns:
    df_valop_temporal[col] = df_valop_temporal[col].astype('category')

print(df_valop_temporal.memory_usage(deep=True).sum() / 1e9, "GB")
df_valop_temporal.head()

0.747240863 GB

,time_step,171_0,666_0,427_0,837_0,167_0,167_1,167_2,167_3,167_4,167_5,167_6,167_7,167_8,167_9,309_0,272_0,272_1,272_2,272_3,272_4,272_5,272_6,272_7,272_8,272_9,835_0,370_0,291_0,291_1,291_2,291_3,291_4,291_5,291_6,291_7,291_8,291_9,291_10,158_0,158_1,158_2,158_3,158_4,158_5,158_6,158_7,158_8,158_9,100_0,459_0,459_1,459_2,459_3,459_4,459_5,459_6,459_7,459_8,459_9,459_10,459_11,459_12,459_13,459_14,459_15,459_16,459_17,459_18,459_19,397_0,397_1,397_2,397_3,397_4,397_5,397_6,397_7,397_8,397_9,397_10,397_11,397_12,397_13,397_14,397_15,397_16,397_17,397_18,397_19,397_20,397_21,397_22,397_23,397_24,397_25,397_26,397_27,397_28,397_29,397_30,397_31,397_32,397_33,397_34,397_35,171_0_last,171_0_mean,171_0_std,171_0_delta,171_0_slope,666_0_last,666_0_mean,666_0_std,666_0_delta,666_0_slope,427_0_last,427_0_mean,427_0_std,427_0_delta,427_0_slope,837_0_last,837_0_mean,837_0_std,837_0_delta,837_0_slope,167_0_last,167_0_mean,167_0_std,167_0_delta,167_0_slope,167_1_last,167_1_mean,167_1_std,167_1_delta,167_1_slope,167_2_last,167_2_mean,167_2_std,167_2_delta,167_2_slope,167_3_last,167_3_mean,167_3_std,167_3_delta,167_3_slope,167_4_last,167_4_mean,167_4_std,167_4_delta,167_4_slope,167_5_last,167_5_mean,167_5_std,167_5_delta,167_5_slope,167_6_last,167_6_mean,167_6_std,167_6_delta,167_6_slope,167_7_last,167_7_mean,167_7_std,167_7_delta,167_7_slope,167_8_last,167_8_mean,167_8_std,167_8_delta,167_8_slope,167_9_last,167_9_mean,167_9_std,167_9_delta,167_9_slope,309_0_last,309_0_mean,309_0_std,309_0_delta,309_0_slope,272_0_last,272_0_mean,272_0_std,272_0_delta,272_0_slope,272_1_last,272_1_mean,272_1_std,272_1_delta,272_1_slope,272_2_last,272_2_mean,272_2_std,272_2_delta,272_2_slope,272_3_last,272_3_mean,272_3_std,272_3_delta,272_3_slope,272_4_last,272_4_mean,272_4_std,272_4_delta,272_4_slope,272_5_last,272_5_mean,272_5_std,272_5_delta,272_5_slope,272_6_last,272_6_mean,272_6_std,272_6_delta,272_6_slope,272_7_last,272_7_mean,272_7_std,272_7_delta,272_7_slope,272_8_last,272_8_mean,272_8_std,272_8_delta,272_8_slope,272_9_last,272_9_mean,272_9_std,272_9_delta,272_9_slope,835_0_last,835_0_mean,835_0_std,835_0_delta,835_0_slope,370_0_last,370_0_mean,370_0_std,370_0_delta,370_0_slope,291_0_last,291_0_mean,291_0_std,291_0_delta,291_0_slope,291_1_last,291_1_mean,291_1_std,291_1_delta,291_1_slope,291_2_last,291_2_mean,291_2_std,291_2_delta,291_2_slope,291_3_last,291_3_mean,291_3_std,291_3_delta,291_3_slope,291_4_last,291_4_mean,291_4_std,291_4_delta,291_4_slope,291_5_last,291_5_mean,291_5_std,291_5_delta,291_5_slope,291_6_last,291_6_mean,291_6_std,291_6_delta,291_6_slope,291_7_last,291_7_mean,291_7_std,291_7_delta,291_7_slope,291_8_last,291_8_mean,291_8_std,291_8_delta,291_8_slope,291_9_last,291_9_mean,291_9_std,291_9_delta,291_9_slope,291_10_last,291_10_mean,291_10_std,291_10_delta,291_10_slope,158_0_last,158_0_mean,158_0_std,158_0_delta,158_0_slope,158_1_last,158_1_mean,158_1_std,158_1_delta,158_1_slope,158_2_last,158_2_mean,158_2_std,158_2_delta,158_2_slope,158_3_last,158_3_mean,158_3_std,158_3_delta,158_3_slope,158_4_last,158_4_mean,158_4_std,158_4_delta,158_4_slope,158_5_last,158_5_mean,158_5_std,158_5_delta,158_5_slope,158_6_last,158_6_mean,158_6_std,158_6_delta,158_6_slope,158_7_last,158_7_mean,158_7_std,158_7_delta,158_7_slope,158_8_last,158_8_mean,158_8_std,158_8_delta,158_8_slope,158_9_last,158_9_mean,158_9_std,158_9_delta,158_9_slope,100_0_last,100_0_mean,100_0_std,100_0_delta,100_0_slope,459_0_last,459_0_mean,459_0_std,459_0_delta,459_0_slope,459_1_last,459_1_mean,459_1_std,459_1_delta,459_1_slope,459_2_last,459_2_mean,459_2_std,459_2_delta,459_2_slope,459_3_last,459_3_mean,459_3_std,459_3_delta,459_3_slope,459_4_last,459_4_mean,459_4_std,459_4_delta,459_4_slope,459_5_last,459_5_mean,459_5_std,459_5_delta,459_5_slope,459_6_last,459_6_mean,459_6_std,459_6_delta,459_6_slope,459_7_last,459_7_mean,459_7_std,459_7_delta,459_7_slope,459_8_last,459_8_mean,459_8_std,459_8_delta,459_8_slope,459_9_last,459_9_mean,459_9_std,459_9_delta,459_9_slope,459_10_last,459_10_mean,459_10_std,459_10_delta,459_10_slope,459_11_last,459_11_mean,459_11_std,459_11_delta,459_11_slope,459_12_last,459_12_mean,459_12_std,459_12_delta,459_12_slope,459_13_last,459_13_mean,459_13_std,459_13_delta,459_13_slope,459_14_last,459_14_mean,459_14_std,459_14_delta,459_14_slope,459_15_last,459_15_mean,459_15_std,459_15_delta,459_15_slope,459_16_last,459_16_mean,459_16_std,459_16_delta,459_16_slope,459_17_last,459_17_mean,459_17_std,459_17_delta,459_17_slope,459_18_last,459_18_mean,459_18_std,459_18_delta,459_18_slope,459_19_last,459_19_mean,459_19_std,459_19_delta,459_19_slope,397_0_last,397_0_mean,397_0_std,397_0_delta,397_0_slope,397_1_last,397_1_mean,397_1_std,397_1_delta,397_1_slope,397_2_last,397_2_mean,397_2_std,397_2_delta,397_2_slope,397_3_last,397_3_mean,397_3_std,397_3_delta,397_3_slope,397_4_last,397_4_mean,397_4_std,397_4_delta,397_4_slope,397_5_last,397_5_mean,397_5_std,397_5_delta,397_5_slope,397_6_last,397_6_mean,397_6_std,397_6_delta,397_6_slope,397_7_last,397_7_mean,397_7_std,397_7_delta,397_7_slope,397_8_last,397_8_mean,397_8_std,397_8_delta,397_8_slope,397_9_last,397_9_mean,397_9_std,397_9_delta,397_9_slope,397_10_last,397_10_mean,397_10_std,397_10_delta,397_10_slope,397_11_last,397_11_mean,397_11_std,397_11_delta,397_11_slope,397_12_last,397_12_mean,397_12_std,397_12_delta,397_12_slope,397_13_last,397_13_mean,397_13_std,397_13_delta,397_13_slope,397_14_last,397_14_mean,397_14_std,397_14_delta,397_14_slope,397_15_last,397_15_mean,397_15_std,397_15_delta,397_15_slope,397_16_last,397_16_mean,397_16_std,397_16_delta,397_16_slope,397_17_last,397_17_mean,397_17_std,397_17_delta,397_17_slope,397_18_last,397_18_mean,397_18_std,397_18_delta,397_18_slope,397_19_last,397_19_mean,397_19_std,397_19_delta,397_19_slope,397_20_last,397_20_mean,397_20_std,397_20_delta,397_20_slope,397_21_last,397_21_mean,397_21_std,397_21_delta,397_21_slope,397_22_last,397_22_mean,397_22_std,397_22_delta,397_22_slope,397_23_last,397_23_mean,397_23_std,397_23_delta,397_23_slope,397_24_last,397_24_mean,397_24_std,397_24_delta,397_24_slope,397_25_last,397_25_mean,397_25_std,397_25_delta,397_25_slope,397_26_last,397_26_mean,397_26_std,397_26_delta,397_26_slope,397_27_last,397_27_mean,397_27_std,397_27_delta,397_27_slope,397_28_last,397_28_mean,397_28_std,397_28_delta,397_28_slope,397_29_last,397_29_mean,397_29_std,397_29_delta,397_29_slope,397_30_last,397_30_mean,397_30_std,397_30_delta,397_30_slope,397_31_last,397_31_mean,397_31_std,397_31_delta,397_31_slope,397_32_last,397_32_mean,397_32_std,397_32_delta,397_32_slope,397_33_last,397_33_mean,397_33_std,397_33_delta,397_33_slope,397_34_last,397_34_mean,397_34_std,397_34_delta,397_34_slope,397_35_last,397_35_mean,397_35_std,397_35_delta,397_35_slope,Spec_0,Spec_1,Spec_2,Spec_3,Spec_4,Spec_5,Spec_6,Spec_7,class_label
vehicle_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10,3.0,46590.0,3696.0,2038959.0,1450.0,0.0,273826.0,339584.0,99834.0,250922.0,1411788.0,357113.0,27034.0,2198.0,0.0,70.0,44098.0,26120.0,12900.0,20960.0,279122.0,12725.0,124.0,0.0,0.0,0.0,2071653.0,0.0,712.0,320.0,353.0,569.0,208.0,48.0,177.0,192.0,120.0,248.0,80.0,21240.0,430191.0,546048.0,166546.0,149355.0,110700.0,83556.0,69345.0,106236.0,99001.0,165052.0,120.700142,40.085209,47.315071,63.458752,77.539238,88.971321,103.708054,123.059586,276.914307,342.500702,217.659729,305.552856,354.001038,604.575684,1479.010742,1283.698608,406.370972,0.191319,0.000000,0.005625,344190.0,249270.0,226995.0,12510.0,11610.0,2040.0,450781.0,134895.0,368565.0,7065.0,1261.0,30.0,27616.0,115141.0,242972.0,7380.0,1696.0,30.0,9181.0,93511.0,141781.0,7187.0,1110.0,15.0,6496.0,74880.0,100725.0,8026.0,855.0,15.0,495.0,91665.0,169125.0,51900.0,9362.0,0.0,46590.0,46590.00,NaN,0.0,NaN,3696.0,3696.0,NaN,0.0,NaN,2038959.0,2.038959e+06,NaN,0.0,NaN,1450.0,1450.0,NaN,0.0,NaN,0.0,0.00,NaN,0.0,NaN,273826.0,273826.0,NaN,0.0,NaN,339584.0,339584.000000,NaN,0.0,NaN,99834.0,99834.0,NaN,0.0,NaN,250922.0,250922.00,NaN,0.0,NaN,1411788.0,1411788.0,NaN,0.0,NaN,357113.0,3.571130e+05,NaN,0.0,NaN,27034.0,27034.0,NaN,0.0,NaN,2198.0,2198.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,70.0,70.00,NaN,0.0,NaN,44098.0,44098.000000,NaN,0.0,NaN,26120.0,26120.000000,NaN,0.0,NaN,12900.0,12900.000000,NaN,0.0,NaN,20960.0,20960.0,NaN,0.0,NaN,279122.0,279122.0,NaN,0.0,NaN,12725.0,12725.0,NaN,0.0,NaN,124.0,124.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,2071653.0,2.071653e+06,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,712.0,712.000000,NaN,0.0,NaN,320.0,320.000000,NaN,0.0,NaN,353.0,353.000000,NaN,0.0,NaN,569.0,569.000000,NaN,0.0,NaN,208.0,208.00,NaN,0.0,NaN,48.0,48.000000,NaN,0.0,NaN,177.0,177.000000,NaN,0.0,NaN,192.0,192.000000,NaN,0.0,NaN,120.0,120.000000,NaN,0.0,NaN,248.0,248.0,NaN,0.0,NaN,80.0,80.000000,NaN,0.0,NaN,21240.0,21240.0,NaN,0.0,NaN,430191.0,430191.0,NaN,0.0,NaN,546048.0,546048.00,NaN,0.0,NaN,166546.0,166546.00,NaN,0.0,NaN,149355.0,149355.00,NaN,0.0,NaN,110700.0,110700.0,NaN,0.0,NaN,83556.0,83556.0,NaN,0.0,NaN,69345.0,69345.00,NaN,0.0,NaN,106236.0,106236.0,NaN,0.0,NaN,99001.0,99001.0,NaN,0.0,NaN,165052.0,165052.00,NaN,0.0,NaN,120.700142,120.700142,NaN,0.000000,NaN,40.085209,40.085209,NaN,0.000000,NaN,47.315071,47.315071,NaN,0.000000,NaN,63.458752,63.458752,NaN,0.000000,NaN,77.539238,77.539238,NaN,0.000000,NaN,88.971321,88.971321,NaN,0.000000,NaN,103.708054,103.708054,NaN,0.000000,NaN,123.059586,123.059586,NaN,0.000000,NaN,276.914307,276.914307,NaN,0.000000,NaN,342.500702,342.500702,NaN,0.000000,NaN,217.659729,217.659729,NaN,0.000000,NaN,305.552856,305.552856,NaN,0.000000,NaN,354.001038,354.001038,NaN,0.000000,NaN,604.575684,604.575684,NaN,0.000000,NaN,1479.010742,1479.010742,NaN,0.000000,NaN,1283.698608,1283.698608,NaN,0.000000,NaN,406.370972,406.370972,NaN,0.000000,NaN,0.191319,0.191319,NaN,0.000000,NaN,0.000000,0.000000,NaN,0.000000,NaN,0.005625,0.005625,NaN,0.000000,NaN,344190.0,3.441900e+05,NaN,0.0,NaN,249270.0,249270.00,NaN,0.0,NaN,226995.0,226995.0,NaN,0.0,NaN,12510.0,12510.000000,NaN,0.0,NaN,11610.0,11610.000000,NaN,0.0,NaN,2040.0,2040.000000,NaN,0.0,NaN,450781.0,4.507810e+05,NaN,0.0,NaN,134895.0,134895.000000,NaN,0.0,NaN,368565.0,368565.0,NaN,0.0,NaN,7065.0,7065.00,NaN,0.0,NaN,1261.0,1261.00,NaN,0.0,NaN,30.0,30.000000,NaN,0.0,NaN,27616.0,27616.000000,NaN,0.0,NaN,115141.0,115141.000000,NaN,0.0,NaN,242972.0,242972.000000,NaN,0.0,NaN,7380.0,7380.000000,NaN,0.0,NaN,1696.0,1696.0,NaN,0.0,NaN,30.0,30.0,NaN,0.0,NaN,9181.0,9181.0,NaN,0.0,NaN,93511.0,93511.00,NaN,0.0,NaN,141781.0,141781.00,NaN,0.0,NaN,7187.0,7187.00,NaN,0.0,NaN,1110.0,1110.0,NaN,0.0,NaN,15.0,15.0,NaN,0.0,NaN,6496.0,6496.000000,NaN,0.0,NaN,74880.0,74880.000000,NaN,0.0,NaN,100725.0,100725.000000,NaN,0.0,NaN,8026.0,8026.0,NaN,0.0,NaN,855.0,855.000000,NaN,0.0,NaN,15.0,15.0,NaN,0.0,NaN,495.0,495.00,NaN,0.0,NaN,91665.0,91665.00,NaN,0.0,NaN,169125.0,169125.000000,NaN,0.0,NaN,51900.0,51900.00,NaN,0.0,NaN,9362.0,9362.00,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,Cat0,Cat0,Cat0,Cat0,Cat0,Cat1,Cat0,Cat1,NaN
10,7.4,127110.0,16716.0,6501456.0,4660.0,0.0,635642.0,609742.0,288036.0,781775.0,4592210.0,1715785.0,82866.0,2198.0,0.0,70.0,106579.0,46710.0,27098.0,56310.0,954252.0,57347.0,124.0,0.0,0.0,0.0,6530228.0,0.0,1648.0,664.0,689.0,1601.0,801.0,409.0,809.0,824.0,1041.0,1488.0,136.0,54936.0,1384740.0,1626471.0,450964.0,410724.0,344925.0,268488.0,232686.0,438867.0,405307.0,496081.0,344.130493,216.756256,324.007568,432.727234,518.133240,589.343323,641.517090,706.043518,1670.332764,1645.494751,1035.262329,1409.725098,1553.562012,2520.997070,4089.285156,1881.583252,443.728546,0.384444,0.010972,0.006667,1259850.0,1042830.0,718113.0,88172.0,85561.0,15570.0,1180141.0,429137.0,612150.0,37126.0,9346.0,616.0,97877.0,382653.0,501799.0,45165.0,12722.0,345.0,39304.0,320401.0,395162.0,48348.0,9840.0,345.0,25368.0,229531.0,295291.0,44312.0,7995.0,75.0,2265.0,414180.0,688891.0,258810.0,63167.0,1005.0,127110.0,86850.00,56936.238021,80520.0,18299.991456,16716.0,10206.0,9206.530291,13020.0,2959.089291,6501456.0,4.270208e+06,3.155462e+06,4462497.0,1.014203e+06,4660.0,3055.0,2269.812768,3210.0,729.545058,0.0,0.00,0.0,0.0,0.000000,635642.0,454734.0,255842.547142,361816.0,82230.872679,609742.0,474663.000000,191030.553792,270158.0,61399.536448,288036.0,193935.0,133078.910433,188202.0,42773.170001,781775.0,516348.50,375369.756113,530853.0,120648.351519,4592210.0,3001999.0,2.248898e+06,3180422.0,722822.961230,1715785.0,1.036449e+06,9.607262e+05,1358672.0,308788.899782,82866.0,54950.0,39479.185807,55832.0,12689.084382,2198.0,2198.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,70.0,70.00,0.000000,0.0,0.000000,106579.0,75338.500000,44180.738795,62481.0,14200.220798,46710.0,36415.000000,14559.328625,20590.0,4679.541619,27098.0,19999.000000,10039.502079,14198.0,3226.816505,56310.0,38635.0,24996.224715,35350.0,8034.084324,954252.0,616687.0,477389.001182,675130.0,153438.562245,57347.0,35036.0,31552.518790,44622.0,10141.359198,124.0,124.0,0.000000,0.0,0.000013,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6530228.0,4.300940e+06,3.152689e+06,4458575.0,1.013312e+06,0.0,0.0,0.0,0.0,0.0,1648.0,1180.000000,661.851947,936.0,212.727119,664.0,492.000000,243.244733,344.0,78.181784,689.0,521.000000,237.587878,336.0,76.363594,1601.0,1085.000000,729.734198,1032.0,234.545303,801.0,504.50,419.314321,593.0,134.772627,409.0,228.500000,255.265548,361.0,82.045407,809.0,493.000000,446.891486,632.0,143.636286,824.0,508.000000,446.891486,632.0,143.636286,1041.0,580.500000,651.245345,921.0,209.318030,1488.0,868.0,876.812409,1240.0,281.818052,136.0,108.000000,39.597980,56.0,12.727270,54936.0,38088.0,23826.670099,33696.0,7658.177478,1384740.0,907465.5,674968.070875,954549.0,216942.797381,1626471.0,1086259.50,763974.429850,1080423.0,245550.625172,450964.0,308755.00,201113.896492,284418.0,64640.417056,410724.0,280039.50,184815.792292,261369.0,59402.017425,344925.0,227812.5,165622.085823,234225.0,53232.910911,268488.0,176022.0,130766.671258,184932.0,42029.975879,232686.0,151015.50,115499.528746,163341.0,37122.929282,438867.0,272551.5,235205.635733,332631.0,75597.897744,405307.0,252154.0,216591.049718,306306.0,69614.948103,496081.0,330566.50,234072.850669,331029.0,75233.822629,344.130493,232.415318,157.989116,223.430359,50.779594,216.756256,128.420732,124.925296,176.671051,40.152487,324.007568,185.661320,195.651141,276.692505,62.884634,432.727234,248.092993,261.112248,369.268494,83.924608,518.133240,297.836239,311.547006,440.593994,100.134927,589.343323,339.157322,353.816435,500.372009,113.720837,641.517090,372.612572,380.288417,537.809021,122.229232,706.043518,414.551552,412.231892,582.983948,132.496270,1670.332764,973.623535,985.295640,1393.418457,316.685844,1645.494751,993.997726,921.355928,1302.994019,296.134769,1035.262329,626.461029,578.132343,817.602600,185.818657,1409.725098,857.638977,780.767679,1104.172241,250.948008,1553.562012,953.781525,848.217699,1199.561035,272.627375,2520.997070,1562.786377,1355.114558,1916.421387,435.550049,4089.285156,2784.147949,1845.742739,2610.274414,593.243880,1881.583252,1582.640930,422.768286,597.884644,135.882911,443.728546,425.049759,26.415794,37.357574,8.490387,0.384444,0.287882,0.136560,0.193125,0.043892,0.010972,0.005486,0.007759,0.010972,0.002494,0.006667,0.006146,0.000737,0.001042,0.000237,1259850.0,8.020200e+05,647469.395261,915660.0,208104.426527,1042830.0,646050.00,561131.657278,793560.0,180354.397620,718113.0,472554.0,347272.868163,491118.0,111617.677103,88172.0,50341.000000,53501.113278,75662.0,17195.898870,85561.0,48585.500000,52291.253576,73951.0,16807.036843,15570.0,8805.000000,9567.154749,13530.0,3074.997479,1180141.0,8.154610e+05,515735.401926,729360.0,165763.603795,429137.0,282016.000000,208060.513510,294242.0,66873.137334,612150.0,490357.5,172240.605295,243585.0,55360.181895,37126.0,22095.50,21256.336949,30061.0,6832.041791,9346.0,5303.50,5716.958326,8085.0,1837.498494,616.0,323.000000,414.364574,586.0,133.181704,97877.0,62746.500000,49682.029553,70261.0,15968.401167,382653.0,248897.000000,189159.549249,267512.0,60798.142313,501799.0,372385.500000,183018.326854,258827.0,58824.331948,45165.0,26272.500000,26718.029727,37785.0,8587.492961,12722.0,7209.0,7796.559369,11026.0,2505.908167,345.0,187.5,222.738636,315.0,71.590863,39304.0,24242.5,21300.177570,30123.0,6846.131720,320401.0,206956.00,160435.457583,226890.0,51565.892649,395162.0,268471.50,179167.423324,253381.0,57586.548871,48348.0,27767.50,29105.222220,41161.0,9354.766996,9840.0,5475.0,6173.042200,8730.0,1984.089686,345.0,180.0,233.345238,330.0,74.999951,25368.0,15932.000000,13344.519175,18872.0,4289.088039,229531.0,152205.500000,109354.770817,154651.0,35147.930900,295291.0,198008.000000,137578.937988,194566.0,44219.527287,44312.0,26169.0,25658.076662,36286.0,8246.813359,7995.0,4425.000000,5048.742418,7140.0,1622.725943,75.0,45.0,42.426407,60.0,13.636356,2265.0,1380.00,1251.579003,1770.0,402.272498,414180.0,252922.50,228052.543534,322515.0,73298.803554,688891.0,429008.000000,367530.063230,519766.0,118128.570527,258810.0,155355.00,146307.464095,206910.0,47024.961454,63167.0,36264.50,38045.880362,53805.0,12228.402296,1005.0,502.5,710.642315,1005.0,228.408904,Cat0,Cat0,Cat0,Cat0,Cat0,Cat1,Cat0,Cat1,NaN

In [14]:
# Temporal aggregates and labels for test set
sensorcols = df_testop.iloc[:, 2:].columns
sensors = [col for col in sensorcols]
df_testop_temporal = add_temporal_aggregates(testop_idx, sensors)
df_testop_temporal = df_testop_temporal.join(df_testspec)
mask = df_testop_temporal.groupby(level=0).cumcount(ascending=False) == 0
df_testop_temporal['class_label'] = np.nan
df_testop_temporal.loc[mask, 'class_label'] = np.asarray(df_testlab['class_label'])

for col in df_testspec.columns:
    df_testop_temporal[col] = df_testop_temporal[col].astype('category')

print(df_testop_temporal.memory_usage(deep=True).sum() / 1e9, "GB")
df_testop_temporal.head()

0.754525567 GB

,time_step,171_0,666_0,427_0,837_0,167_0,167_1,167_2,167_3,167_4,167_5,167_6,167_7,167_8,167_9,309_0,272_0,272_1,272_2,272_3,272_4,272_5,272_6,272_7,272_8,272_9,835_0,370_0,291_0,291_1,291_2,291_3,291_4,291_5,291_6,291_7,291_8,291_9,291_10,158_0,158_1,158_2,158_3,158_4,158_5,158_6,158_7,158_8,158_9,100_0,459_0,459_1,459_2,459_3,459_4,459_5,459_6,459_7,459_8,459_9,459_10,459_11,459_12,459_13,459_14,459_15,459_16,459_17,459_18,459_19,397_0,397_1,397_2,397_3,397_4,397_5,397_6,397_7,397_8,397_9,397_10,397_11,397_12,397_13,397_14,397_15,397_16,397_17,397_18,397_19,397_20,397_21,397_22,397_23,397_24,397_25,397_26,397_27,397_28,397_29,397_30,397_31,397_32,397_33,397_34,397_35,171_0_last,171_0_mean,171_0_std,171_0_delta,171_0_slope,666_0_last,666_0_mean,666_0_std,666_0_delta,666_0_slope,427_0_last,427_0_mean,427_0_std,427_0_delta,427_0_slope,837_0_last,837_0_mean,837_0_std,837_0_delta,837_0_slope,167_0_last,167_0_mean,167_0_std,167_0_delta,167_0_slope,167_1_last,167_1_mean,167_1_std,167_1_delta,167_1_slope,167_2_last,167_2_mean,167_2_std,167_2_delta,167_2_slope,167_3_last,167_3_mean,167_3_std,167_3_delta,167_3_slope,167_4_last,167_4_mean,167_4_std,167_4_delta,167_4_slope,167_5_last,167_5_mean,167_5_std,167_5_delta,167_5_slope,167_6_last,167_6_mean,167_6_std,167_6_delta,167_6_slope,167_7_last,167_7_mean,167_7_std,167_7_delta,167_7_slope,167_8_last,167_8_mean,167_8_std,167_8_delta,167_8_slope,167_9_last,167_9_mean,167_9_std,167_9_delta,167_9_slope,309_0_last,309_0_mean,309_0_std,309_0_delta,309_0_slope,272_0_last,272_0_mean,272_0_std,272_0_delta,272_0_slope,272_1_last,272_1_mean,272_1_std,272_1_delta,272_1_slope,272_2_last,272_2_mean,272_2_std,272_2_delta,272_2_slope,272_3_last,272_3_mean,272_3_std,272_3_delta,272_3_slope,272_4_last,272_4_mean,272_4_std,272_4_delta,272_4_slope,272_5_last,272_5_mean,272_5_std,272_5_delta,272_5_slope,272_6_last,272_6_mean,272_6_std,272_6_delta,272_6_slope,272_7_last,272_7_mean,272_7_std,272_7_delta,272_7_slope,272_8_last,272_8_mean,272_8_std,272_8_delta,272_8_slope,272_9_last,272_9_mean,272_9_std,272_9_delta,272_9_slope,835_0_last,835_0_mean,835_0_std,835_0_delta,835_0_slope,370_0_last,370_0_mean,370_0_std,370_0_delta,370_0_slope,291_0_last,291_0_mean,291_0_std,291_0_delta,291_0_slope,291_1_last,291_1_mean,291_1_std,291_1_delta,291_1_slope,291_2_last,291_2_mean,291_2_std,291_2_delta,291_2_slope,291_3_last,291_3_mean,291_3_std,291_3_delta,291_3_slope,291_4_last,291_4_mean,291_4_std,291_4_delta,291_4_slope,291_5_last,291_5_mean,291_5_std,291_5_delta,291_5_slope,291_6_last,291_6_mean,291_6_std,291_6_delta,291_6_slope,291_7_last,291_7_mean,291_7_std,291_7_delta,291_7_slope,291_8_last,291_8_mean,291_8_std,291_8_delta,291_8_slope,291_9_last,291_9_mean,291_9_std,291_9_delta,291_9_slope,291_10_last,291_10_mean,291_10_std,291_10_delta,291_10_slope,158_0_last,158_0_mean,158_0_std,158_0_delta,158_0_slope,158_1_last,158_1_mean,158_1_std,158_1_delta,158_1_slope,158_2_last,158_2_mean,158_2_std,158_2_delta,158_2_slope,158_3_last,158_3_mean,158_3_std,158_3_delta,158_3_slope,158_4_last,158_4_mean,158_4_std,158_4_delta,158_4_slope,158_5_last,158_5_mean,158_5_std,158_5_delta,158_5_slope,158_6_last,158_6_mean,158_6_std,158_6_delta,158_6_slope,158_7_last,158_7_mean,158_7_std,158_7_delta,158_7_slope,158_8_last,158_8_mean,158_8_std,158_8_delta,158_8_slope,158_9_last,158_9_mean,158_9_std,158_9_delta,158_9_slope,100_0_last,100_0_mean,100_0_std,100_0_delta,100_0_slope,459_0_last,459_0_mean,459_0_std,459_0_delta,459_0_slope,459_1_last,459_1_mean,459_1_std,459_1_delta,459_1_slope,459_2_last,459_2_mean,459_2_std,459_2_delta,459_2_slope,459_3_last,459_3_mean,459_3_std,459_3_delta,459_3_slope,459_4_last,459_4_mean,459_4_std,459_4_delta,459_4_slope,459_5_last,459_5_mean,459_5_std,459_5_delta,459_5_slope,459_6_last,459_6_mean,459_6_std,459_6_delta,459_6_slope,459_7_last,459_7_mean,459_7_std,459_7_delta,459_7_slope,459_8_last,459_8_mean,459_8_std,459_8_delta,459_8_slope,459_9_last,459_9_mean,459_9_std,459_9_delta,459_9_slope,459_10_last,459_10_mean,459_10_std,459_10_delta,459_10_slope,459_11_last,459_11_mean,459_11_std,459_11_delta,459_11_slope,459_12_last,459_12_mean,459_12_std,459_12_delta,459_12_slope,459_13_last,459_13_mean,459_13_std,459_13_delta,459_13_slope,459_14_last,459_14_mean,459_14_std,459_14_delta,459_14_slope,459_15_last,459_15_mean,459_15_std,459_15_delta,459_15_slope,459_16_last,459_16_mean,459_16_std,459_16_delta,459_16_slope,459_17_last,459_17_mean,459_17_std,459_17_delta,459_17_slope,459_18_last,459_18_mean,459_18_std,459_18_delta,459_18_slope,459_19_last,459_19_mean,459_19_std,459_19_delta,459_19_slope,397_0_last,397_0_mean,397_0_std,397_0_delta,397_0_slope,397_1_last,397_1_mean,397_1_std,397_1_delta,397_1_slope,397_2_last,397_2_mean,397_2_std,397_2_delta,397_2_slope,397_3_last,397_3_mean,397_3_std,397_3_delta,397_3_slope,397_4_last,397_4_mean,397_4_std,397_4_delta,397_4_slope,397_5_last,397_5_mean,397_5_std,397_5_delta,397_5_slope,397_6_last,397_6_mean,397_6_std,397_6_delta,397_6_slope,397_7_last,397_7_mean,397_7_std,397_7_delta,397_7_slope,397_8_last,397_8_mean,397_8_std,397_8_delta,397_8_slope,397_9_last,397_9_mean,397_9_std,397_9_delta,397_9_slope,397_10_last,397_10_mean,397_10_std,397_10_delta,397_10_slope,397_11_last,397_11_mean,397_11_std,397_11_delta,397_11_slope,397_12_last,397_12_mean,397_12_std,397_12_delta,397_12_slope,397_13_last,397_13_mean,397_13_std,397_13_delta,397_13_slope,397_14_last,397_14_mean,397_14_std,397_14_delta,397_14_slope,397_15_last,397_15_mean,397_15_std,397_15_delta,397_15_slope,397_16_last,397_16_mean,397_16_std,397_16_delta,397_16_slope,397_17_last,397_17_mean,397_17_std,397_17_delta,397_17_slope,397_18_last,397_18_mean,397_18_std,397_18_delta,397_18_slope,397_19_last,397_19_mean,397_19_std,397_19_delta,397_19_slope,397_20_last,397_20_mean,397_20_std,397_20_delta,397_20_slope,397_21_last,397_21_mean,397_21_std,397_21_delta,397_21_slope,397_22_last,397_22_mean,397_22_std,397_22_delta,397_22_slope,397_23_last,397_23_mean,397_23_std,397_23_delta,397_23_slope,397_24_last,397_24_mean,397_24_std,397_24_delta,397_24_slope,397_25_last,397_25_mean,397_25_std,397_25_delta,397_25_slope,397_26_last,397_26_mean,397_26_std,397_26_delta,397_26_slope,397_27_last,397_27_mean,397_27_std,397_27_delta,397_27_slope,397_28_last,397_28_mean,397_28_std,397_28_delta,397_28_slope,397_29_last,397_29_mean,397_29_std,397_29_delta,397_29_slope,397_30_last,397_30_mean,397_30_std,397_30_delta,397_30_slope,397_31_last,397_31_mean,397_31_std,397_31_delta,397_31_slope,397_32_last,397_32_mean,397_32_std,397_32_delta,397_32_slope,397_33_last,397_33_mean,397_33_std,397_33_delta,397_33_slope,397_34_last,397_34_mean,397_34_std,397_34_delta,397_34_slope,397_35_last,397_35_mean,397_35_std,397_35_delta,397_35_slope,Spec_0,Spec_1,Spec_2,Spec_3,Spec_4,Spec_5,Spec_6,Spec_7,class_label
vehicle_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,4.4,94410.0,7982.0,3115020.0,2625.0,1304.0,366624.0,232040.0,147104.0,422728.0,1651432.0,223425.0,55640.0,8816.0,3449.0,35.0,589556.0,165737.0,107063.0,255684.0,3008236.0,173097.0,6589.0,0.0,0.0,0.0,4466869.0,23994.0,328.0,184.0,237.0,329.0,104.0,48.0,84.0,76.0,60.0,144.0,28.0,132118.0,1565102.0,1976016.0,469225.0,314398.0,312200.0,194684.0,135352.0,150738.0,230483.0,232410.0,199.198837,54.364944,45.376778,51.823891,63.903610,77.826614,103.357330,122.073776,445.946655,548.500916,347.169159,372.139374,386.215179,499.586212,801.094971,3222.756836,2.499500,0.111111,0.019500,0.000000,263249.0,239652.0,280203.0,26432.0,21462.0,2674.0,409690.0,144340.0,519841.0,5432.0,1408.0,77.0,53152.0,67929.0,242384.0,5194.0,1653.0,63.0,8961.0,41455.0,127793.0,6974.0,952.0,14.0,5489.0,29540.0,72548.0,9696.0,1309.0,7.0,399.0,31843.0,89138.0,24101.0,5112.0,7.0,94410.0,94410.00,NaN,0.0,NaN,7982.0,7982.000000,NaN,0.0,NaN,3115020.0,3.115020e+06,NaN,0.0,NaN,2625.0,2625.00,NaN,0.0,NaN,1304.0,1304.00,NaN,0.0,NaN,366624.0,366624.000000,NaN,0.0,NaN,232040.0,232040.000000,NaN,0.0,NaN,147104.0,147104.000000,NaN,0.0,NaN,422728.0,422728.000000,NaN,0.0,NaN,1651432.0,1651432.0,NaN,0.0,NaN,223425.0,223425.0,NaN,0.0,NaN,55640.0,55640.000000,NaN,0.0,NaN,8816.0,8816.000000,NaN,0.0,NaN,3449.0,3449.000000,NaN,0.0,NaN,35.0,35.000000,NaN,0.0,NaN,589556.0,589556.000000,NaN,0.0,NaN,165737.0,165737.000000,NaN,0.0,NaN,107063.0,107063.0,NaN,0.0,NaN,255684.0,255684.000000,NaN,0.0,NaN,3008236.0,3008236.0,NaN,0.0,NaN,173097.0,173097.00,NaN,0.0,NaN,6589.0,6589.000000,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,0.0,0.0,NaN,0.0,NaN,4466869.0,4.466869e+06,NaN,0.0,NaN,23994.0,23994.0,NaN,0.0,NaN,328.0,328.000000,NaN,0.0,NaN,184.0,184.0,NaN,0.0,NaN,237.0,237.000000,NaN,0.0,NaN,329.0,329.000000,NaN,0.0,NaN,104.0,104.00,NaN,0.0,NaN,48.0,48.0,NaN,0.0,NaN,84.0,84.000000,NaN,0.0,NaN,76.0,76.000000,NaN,0.0,NaN,60.0,60.000000,NaN,0.0,NaN,144.0,144.0,NaN,0.0,NaN,28.0,28.000000,NaN,0.0,NaN,132118.0,132118.000000,NaN,0.0,NaN,1565102.0,1565102.0,NaN,0.0,NaN,1976016.0,1.976016e+06,NaN,0.0,NaN,469225.0,4.692250e+05,NaN,0.0,NaN,314398.0,314398.0,NaN,0.0,NaN,312200.0,312200.000000,NaN,0.0,NaN,194684.0,194684.000000,NaN,0.0,NaN,135352.0,135352.0,NaN,0.0,NaN,150738.0,150738.000000,NaN,0.0,NaN,230483.0,230483.000000,NaN,0.0,NaN,232410.0,232410.000000,NaN,0.0,NaN,199.198837,199.198837,NaN,0.000000,NaN,54.364944,54.364944,NaN,0.000000,NaN,45.376778,45.376778,NaN,0.000000,NaN,51.823891,51.823891,NaN,0.000000,NaN,63.903610,63.903610,NaN,0.000000,NaN,77.826614,77.826614,NaN,0.000000,NaN,103.357330,103.357330,NaN,0.000000,NaN,122.073776,122.073776,NaN,0.000000,NaN,445.946655,445.946655,NaN,0.000000,NaN,548.500916,548.500916,NaN,0.000000,NaN,347.169159,347.169159,NaN,0.000000,NaN,372.139374,372.139374,NaN,0.000000,NaN,386.215179,386.215179,NaN,0.000000,NaN,499.586212,499.586212,NaN,0.000000,NaN,801.094971,801.094971,NaN,0.000000,NaN,3222.756836,3222.756836,NaN,0.000000,NaN,2.499500,2.499500,NaN,0.000000,NaN,0.111111,0.111111,NaN,0.000000,NaN,0.019500,0.019500,NaN,0.000000,NaN,0.000000,0.000000,NaN,0.000000,NaN,263249.0,263249.000000,NaN,0.0,NaN,239652.0,239652.00,NaN,0.0,NaN,280203.0,280203.00,NaN,0.0,NaN,26432.0,26432.000000,NaN,0.0,NaN,21462.0,21462.000000,NaN,0.0,NaN,2674.0,2674.00,NaN,0.0,NaN,409690.0,409690.00,NaN,0.0,NaN,144340.0,144340.000000,NaN,0.0,NaN,519841.0,519841.000000,NaN,0.0,NaN,5432.0,5432.000000,NaN,0.0,NaN,1408.0,1408.0,NaN,0.0,NaN,77.0,77.000000,NaN,0.0,NaN,53152.0,53152.000000,NaN,0.0,NaN,67929.0,67929.000000,NaN,0.0,NaN,242384.0,242384.000000,NaN,0.0,NaN,5194.0,5194.0,NaN,0.0,NaN,1653.0,1653.000000,NaN,0.0,NaN,63.0,63.000000,NaN,0.0,NaN,8961.0,8961.000000,NaN,0.0,NaN,41455.0,41455.000000,NaN,0.0,NaN,127793.0,127793.000000,NaN,0.0,NaN,6974.0,6974.00,NaN,0.0,NaN,952.0,952.0,NaN,0.0,NaN,14.0,14.0,NaN,0.0,NaN,5489.0,5489.000000,NaN,0.0,NaN,29540.0,29540.00,NaN,0.0,NaN,72548.0,72548.000000,NaN,0.0,NaN,9696.0,9696.000000,NaN,0.0,NaN,1309.0,1309.000000,NaN,0.0,NaN,7.0,7.000000,NaN,0.0,NaN,399.0,399.0,NaN,0.0,NaN,31843.0,31843.000000,NaN,0.0,NaN,89138.0,89138.000000,NaN,0.0,NaN,24101.0,24101.00,NaN,0.0,NaN,5112.0,5112.000000,NaN,0.0,NaN,7.0,7.000000,NaN,0.0,NaN,Cat0,Cat1,Cat1,Cat0,Cat0,Cat0,Cat0,Cat1,NaN
1,5.0,105405.0,9178.0,3467240.0,3225.0,1305.0,390896.0,252528.0,157824.0,449489.0,1856800.0,253593.0,67992.0,11048.0,3449.0,60.0,623008.0,185878.0,118129.0,267289.0,3361479.0,202841.0,6589.0,0.0,0.0,0.0,4943701.0,25893.0,342.0,196.0,251.0,345.0,113.0,48.0,100.0,92.0,62.0,162.0,30.0,158088.0,1716134.0,2127496.0,512135.0,355586.0,365554.0,229474.0,154686.0,173390.0,272595.0,249265.0,214.559448,57.916779,49.396221,56.415222,71.142891,86.661110,118.600891,144.118439,504.530731,608.976990,388.656494,417.743713,433.819458,581.277527,895.922424,3680.537109,3.353833,0.157056,0.021611,0.005111,293265.0,264698.0,322332.0,31124.0,26328.0,3465.0,437361.0,152455.0,547904.0,5839.0,1569.0,105.0,57192.0,74224.0,278030.0,5866.0,1934.0,70.0,9713.0,46425.0,150488.0,7906.0,1113.0,14.0,6177.0,33769.0,83147.0,12042.0,1841.0,7.0,455.0,35749.0,106366.0,28168.0,5420.0,7.0,105405.0,99907.50,7774.639059,10995.0,18324.927798,9178.0,8580.000000,845.699710,1196.0,1993.270350,3467240.0,3.291130e+06,2.490572e+05,352220.0,5.870310e+05,3225.0,2925.00,424.264069,600.0,999.987963,1305.0,1304.50,0.707107,1.0,1.665543,390896.0,378760.000000,17162.895793,24272.0,40453.240765,252528.0,242284.000000,14487.203733,20488.0,34146.440672,157824.0,152464.000000,7580.184694,10720.0,17866.952169,449489.0,436108.500000,18922.884571,26761.0,44601.756925,1856800.0,1754116.0,1.452171e+05,205368.0,342275.499269,253593.0,238509.0,2.133200e+04,30168.0,50279.404751,67992.0,61816.000000,8734.182961,12352.0,20586.334372,11048.0,9932.000000,1578.262336,2232.0,3719.966940,3449.0,3449.000000,0.000000,0.0,0.010850,60.0,47.500000,17.677670,25.0,41.665883,623008.0,606282.000000,23654.136044,33452.0,55754.279441,185878.0,175807.500000,14241.837680,20141.0,33567.981690,118129.0,112596.0,7824.843641,11066.0,18443.327866,267289.0,261486.500000,8205.974196,11605.0,19341.223981,3361479.0,3184857.5,2.497805e+05,353243.0,5.887421e+05,202841.0,187969.00,21032.184100,29744.0,49572.476487,6589.0,6589.000000,0.000000,0.0,0.021701,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4943701.0,4.705285e+06,3.371711e+05,476832.0,7.947151e+05,25893.0,24943.5,1342.795777,1899.0,3164.944921,342.0,335.000000,9.899495,14.0,23.335241,196.0,190.0,8.485281,12.0,20.000763,251.0,244.000000,9.899495,14.0,23.333884,345.0,337.000000,11.313708,16.0,26.667684,113.0,108.50,6.363961,9.0,14.999725,48.0,48.0,0.000000,0.0,0.000170,100.0,92.000000,11.313708,16.0,26.665989,92.0,84.000000,11.313708,16.0,26.666328,62.0,61.000000,1.414214,2.0,3.333460,162.0,153.0,12.727922,18.0,30.000127,30.0,29.000000,1.414214,2.0,3.333460,158088.0,145103.000000,18363.563107,25970.0,43283.037108,1716134.0,1640618.0,1.067958e+05,151032.0,251716.460890,2127496.0,2.051756e+06,1.071125e+05,151480.0,252471.999152,512135.0,4.906800e+05,30341.951981,42910.0,71515.029818,355586.0,334992.0,29124.314104,41188.0,68645.651048,365554.0,338877.000000,37726.975203,53354.0,88921.575858,229474.0,212079.000000,24600.244917,34790.0,57982.700659,154686.0,145019.0,13671.202507,19334.0,32222.873588,173390.0,162064.000000,16017.382807,22652.0,37753.302562,272595.0,251539.000000,29777.680769,42112.0,70185.893572,249265.0,240837.500000,11918.284797,16855.0,28091.023714,214.559448,206.879143,10.861592,15.360611,25.600949,57.916779,56.140862,2.511526,3.551834,5.919936,49.396221,47.386499,2.842176,4.019444,6.699133,56.415222,54.119556,3.246562,4.591331,7.652277,71.142891,67.523251,5.118944,7.239281,12.065357,86.661110,82.243862,6.246932,8.834496,14.724055,118.600891,110.979111,10.778825,15.243561,25.405641,144.118439,133.096107,15.587930,22.044662,36.740967,504.530731,475.238693,41.425197,58.584076,97.637739,608.976990,578.738953,42.763042,60.476074,100.792506,388.656494,367.912827,29.335976,41.487335,69.143111,417.743713,394.941544,32.247138,45.604340,76.007375,433.819458,410.017319,33.661308,47.604279,79.337106,581.277527,540.431870,57.764483,81.691315,136.151398,895.922424,848.508698,67.053135,94.827454,158.047598,3680.537109,3451.646973,323.699536,457.780273,762.959968,3.353833,2.926667,0.604105,0.854333,1.423867,0.157056,0.134083,0.032488,0.045944,0.076573,0.021611,0.020556,0.001493,0.002111,0.003518,0.005111,0.002556,0.003614,0.005111,0.008518,293265.0,278257.000000,21224.517144,30016.0,50025.243902,264698.0,252175.00,17710.196442,25046.0,41743.489012,322332.0,301267.50,29789.701585,42129.0,70213.670714,31124.0,28778.000000,3317.745017,4692.0,7819.959904,26328.0,23895.000000,3440.781597,4866.0,8109.970628,3465.0,3069.50,559.321464,791.0,1318.318350,437361.0,423525.50,19566.351742,27671.0,46118.388878,152455.0,148397.500000,5738.171529,8115.0,13524.690444,547904.0,533872.500000,19843.537600,28063.0,46771.151716,5839.0,5635.500000,287.792460,407.0,678.326488,1569.0,1488.5,113.844192,161.0,268.331532,105.0,91.000000,19.798990,28.0,46.666073,57192.0,55172.000000,2856.711396,4040.0,6733.352830,74224.0,71076.500000,4451.237188,6295.0,10491.773751,278030.0,260207.000000,25205.528322,35646.0,59408.362473,5866.0,5530.0,475.175757,672.0,1120.004747,1934.0,1793.500000,198.697006,281.0,468.326954,70.0,66.500000,4.949747,7.0,11.666603,9713.0,9337.000000,531.744299,752.0,1253.356730,46425.0,43940.000000,3514.320702,4970.0,8283.317354,150488.0,139140.500000,16047.788399,22695.0,37824.828703,7906.0,7440.00,659.023520,932.0,1553.306462,1113.0,1032.5,113.844192,161.0,268.331532,14.0,14.0,0.000000,0.0,0.000085,6177.0,5833.000000,486.489465,688.0,1146.653443,33769.0,31654.50,2990.354578,4229.0,7048.276178,83147.0,77847.500000,7494.624774,10599.0,17664.873461,12042.0,10869.000000,1658.872509,2346.0,3909.979952,1841.0,1575.000000,376.180808,532.0,886.649628,7.0,7.000000,0.000000,0.0,0.000042,455.0,427.0,39.597980,56.0,93.332825,35749.0,33796.000000,2761.959087,3906.0,6509.920444,106366.0,97752.000000,12182.035626,17228.0,28713.231695,28168.0,26134.50,2875.803279,4067.0,6778.230275,5420.0,5266.000000,217.788889,308.0,513.334605,7.0,7.000000,0.000000,0.0,0.000042,Cat0,Cat1,Cat1,Cat0,Cat0,Cat0,Cat0,Cat1,NaN

In [ ]:
# Save DataFrames as new feature-engineered CSV files

# Temporal aggregate train readouts
df_trainop_temporal.reset_index().to_parquet(
    "../data/fe_data/temporal_train.parquet",
    index=False
)

# Temporal aggregate val set
df_valop_temporal.reset_index().to_parquet(
    "../data/fe_data/temporal_val.parquet",
    index=False
)

# Temporal aggregate test set
df_testop_temporal.reset_index().to_parquet(
    "../data/fe_data/temporal_test.parquet",
    index=False
)